language: rust

sudo: required

rust:
  - stable
  - beta
  - nightly

os:
  - windows
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - cmake
      - gcc

language: rust

cache: cargo

script:
  - cargo test --verbose --all
  - cargo test --verbose --all --no-default-features
  - cargo test --release --verbose --all
  - cargo test --release --verbose --all --no-default-features
