[package]
name = "mimalloc"
version = "0.1.0"
authors = ["Octavian Oncescu <octavonce@gmail.com>"]
edition = "2018"
repository = "https://github.com/purpleprotocol/mimalloc_rust"
keywords = ["allocator", "encrypted-heap", "performance"]
categories = ["allocator"]
description = "Performance and security oriented drop-in allocator"
license = "MIT"
readme = "README.md"

[dependencies]
libc = "0.2"
libmimalloc-sys = { path = "libmimalloc-sys", version = "0.1.0" }

[features]
no_secure = ["libmimalloc-sys/no_secure"]