[package]
name = "libmimalloc-sys"
version = "0.1.0"
authors = ["Octavian Oncescu <octavonce@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"

[build-dependencies]
cmake = "0.1"

[features]
no_secure = []