[package]
name = "libmimalloc-sys"
version = "0.1.13"
authors = ["Octavian Oncescu <octavonce@gmail.com>"]
edition = "2018"
repository = "https://github.com/purpleprotocol/mimalloc_rust/tree/master/libmimalloc-sys"
keywords = ["allocator", "encrypted-heap", "performance"]
categories = ["allocator"]
description = "Sys crate wrapping the mimalloc allocator"
license = "MIT"

[dependencies]

[build-dependencies]
cmake = "0.1"

[features]
secure = []
secure-full = []